# Domain redirects
[[redirects]]
  from = "http://another-pomodoro.netlify.app/*"
  to = "https://another-pomodoro.app/*"
  status = 301
  force = true

[[redirects]]
  from = "https://another-pomodoro.netlify.app/*"
  to = "https://another-pomodoro.app/*"
  status = 301
  force = true

# Proxying for third-party scripts
[[redirects]]
  from = "/bee.js"
  to = "https://cdn.splitbee.io/sb.js"
  status = 200

[[redirects]]
  from = "/_hive/*"
  to  = "https://hive.splitbee.io/:splat"
  status = 200
