# This workflow will do a clean installation of node dependencies, cache/restore them and build the source code when PRs are submitted against `develop` or when new tags (releases) are pushed.

name: CI

on:
  pull_request:
    branches: [ develop ]
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build (Node 20)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Enable Corepack before setting up Node  
      run: corepack enable
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        architecture: 'x64'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --immutable
    - name: Build app
      run: yarn generate:modern
